elixirs/faker

- README.md
- lib/faker/avatar.ex
- lib/faker/commerce.ex
- mix.exs
I adapted some code to the style defined in https://github.com/niftyn8/elixir_style_guide. Just a couple of extra spaces and some use of the `|>` operator.
I also did some *minor* changes to the formatting of README.md and `mix.exs`.
> Adapt code style to github.com/niftyn8/elixir_style_guide

- priv/internet.json
removed lorempixum since their TLS cert is invalid.
Unless http is explicitly needed, this would be helpful as Chrome prevents loading insecure resources from secure sites.
> Changed image_urls to https

- lib/faker/phone/en_gb.ex
- test/faker/phone_test.exs
Hey there,
This PR contains a generator for UK Phone Numbers. It uses the "en" locale, but ideally locales would be based on country (and so this generator should be under "en_GB").
Let me know what you think,
JH
> Add UK Phone Number generator

- lib/faker/phone/en_us.ex
- test/faker/phone/en_us_test.exs
Hello. This PR adds US phone number support, though it suffers the same locale issues as PR #41/issue #23... Would `phone_us` and `phone_uk` work around the locale issue until it can be sorted?
> Add US phone number generator

- lib/faker/phone/en_gb.ex
The extra import was producing a warning when faker is compiled.
> Remove unnecessary import in lib/faker/en_gb.ex

- lib/faker/nato.ex
- test/faker/nato_test.exs
Adds a module for generating strings from the [nato phonetic alphabet](https://en.wikipedia.org/wiki/NATO_phonetic_alphabet). I've found this really useful for generating categories/severity levels/team names etc.
Examples
---------
```
Faker.Nato.letter_code_word
Faker.Nato.digit_code_word
Faker.Nato.format("?-#-?")
Faker.Nato.callsign
```
@igas what do you think? I made use of it in the ruby [ffaker](https://github.com/ffaker/ffaker) gem. Be awesome to have access to it in elixir too. (Cheers for putting together this library by the way - exactly what I was looking for).
> Support NATO phoentic alphabet

- test/faker/date_test.exs
The dates in Faker.Date's forward/1 and backward/1 aren't correctly compared in the tests. This PR fixes that.
> Dates are now compared without failure

- lib/faker/date.ex
The date tests for forward and backward are still randomly failing because they might return today's date while the tests compare if the date is actually in the future/past. I had to either change the tests to allow today's date or change the forward/backward functions to not return today.
I found changing forward/1 and backward/1 to no longer return today's date randomly to be a better solution.
> Faker.Date.forward/1 and .backward/1 no longer includes today

- lib/faker/lorem.ex
The function `Faker.Lorem.paragraphs/1` type specification declares a `String.t` return type, but the function does actually return a `list(String.t)` (in fact, the tests were already checking if the returned value was a list).
You can see this incorrect type specification in the following example:
```elixir
iex(1)> s Faker.Lorem.paragraphs
@spec paragraphs(integer()) :: String.t()
@spec paragraphs(Range.t()) :: String.t()
iex(2)> is_list(Faker.Lorem.paragraphs)
true
```
Dialyzer was also emitting the following type error on this function:
```
lib/faker/lorem.ex:60: Invalid type specification for function 'Elixir.Faker.Lorem':paragraphs/1. The success typing is (integer() | #{'__struct__':='Elixir.Range', 'first':=binary() | integer(), 'last':=integer(), _=>_}) -> [any()]
```
After …
> Fix Faker.Lorem.paragraphs/1 typespec

- CHANGELOG.md
- USAGE.md
- lib/faker/date.ex
- lib/faker/datetime.ex
- lib/faker/naivedatetime.ex
- test/faker/date_test.exs
- test/faker/datetime_test.exs
- test/faker/naivedatetime_test.exs
@igas @tobyhinloopen 
This is currently a work in progress. I just want to get some feedback on what I've accomplished so far and see if this is something you'd accept.
I've gone ahead and implemented support for `DateTime`. This includes the `forward/1` and `backward/1` functions. I've also implemented a `between/2` function that I thought may accomplish what #74 is trying to achieve. If not I think it would still be useful.
I also standardized the relevant `Faker.Date` functions around `Faker.DateTime`. This way all the logic is shared.
If what I've put together so far looks good I'll implement support for `NaiveDateTime` next.
I've added:
> Add support for DateTime and NaiveDateTime

- lib/faker/date.ex
- test/faker/date_test.exs
So, this started out as a supposedly easy hacktoberfest PR,  trying to fix #103 and #96.
I ended up rewriting Faker.Date.date_of_birth to cover the full range of possible birthdays (if not mistaken, including situations involving leapyears), thus hopefully also covering #100 :tada:
Feel free to scrutinize, would be happy about feedback :)
I've added:
> Corrected dateranges for Faker.Date.date_of_birth

- CHANGELOG.md
- USAGE.md
- lib/faker/internet/es.ex
- lib/faker/internet/pt_br.ex
- test/faker/internet/en.exs
- test/faker/internet/es.exs
- test/faker/internet/pt-br.exs
Add translations for Faker.Internet API
I've added:
This PR is related to https://github.com/igas/faker/issues/149
> Faker.Internet.En, Faker.Internet.Es, Faker.Internet.PtBr APIs 

- lib/faker/cat/en.ex
> Fix comment

- lib/faker/pokemon.ex
This fixes a misspelled word in the Pokemon docs.
I've added:
> Fixes misspelling in documentation

- CHANGELOG.md
- lib/faker/lorem.ex
Why:
* Compiling the project with Elixir 1.7 is currently showing multiple
warnings regarding the `Faker.Lorem` module:
```
warning: redefining @doc attribute previously set at line X. If you
want to redefine a previously specified doc, use a definition
without a body after the original documentation
```
These warnings are shown because the same functions (with the same
arities) are being documented twice, depending on whether the
arguments are numbers or ranges.
As this is the same function for Elixir, despite the provided
argument, the second `@doc` definition is overriding the first one.
In fact, this is causing the documentation in [hexdocs] to show
examples using ranges, but only the documentation for numbers.
This change addresses the issue by:
* Refactoring the Faker.Lorem …
> Fix Faker.Lorem documentation

- lib/faker/util.ex
In the former `Faker.Utils.pick/1` the provided `Enum.t()` would be enumerated turning it into a list. With the update a provided Range.t() `low..high` is no longer enumerated and is used to generate a number between the `low` and `high` with the `Faker.random_between/2` function.
I think this resolves issue #213
> Add range matching clause to Faker.Util.pick/1 to avoid enumeration

- CHANGELOG.md
- lib/faker/util.ex
Removed `Enum.to_list/1` call since `Enum.at/2` works fine with any enum.
Fixes #213 and fixes #219.
I've added:
> Fix performance regression

- USAGE.md
I've added:
Edits to these files
> Broken link to lib/faker/code/en.ex removed

- CHANGELOG.md
- lib/faker/internet.ex
Moved the implementation to `Faker.Util`.
Fixes #211
I've added:
> Fixed: Quotes removal in `Faker.Internet` functions

- CHANGELOG.md
- lib/faker/datetime.ex
After upgrading to elixir 1.8.0-rc.1 I started to get these warnings:
```
warning: deprecated time unit: :microseconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
(elixir) lib/calendar/iso.ex:717: Calendar.ISO.precision_for_unit/1
(elixir) lib/calendar/iso.ex:708: Calendar.ISO.from_unix/2
(elixir) lib/calendar/datetime.ex:118: DateTime.from_unix/3
(elixir) lib/calendar/datetime.ex:166: DateTime.from_unix!/3
(faker) lib/faker/date.ex:64: Faker.Date.forward/1
test/faker/date_test.exs:19: Faker.DateTest."test forward/1"/1
(ex_unit) lib/ex_unit/runner.ex:355: ExUnit.Runner.exec_test/1
(stdlib) timer.erl:166: :timer.tc/1
(ex_unit) lib/ex_unit/runner.ex:306: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4
```
I've added:
~~- [ ] USAGE.md …
> 👕  Fix deprecated warning message for microseconds unit

- CHANGELOG.md
- lib/faker/datetime.ex
This enables documentation to be generated for `Faker.DateTime`.
This'll close [#244][1].
I've added:
[1]: https://github.com/igas/faker/issues/244
> Updated Documentation

- lib/faker/uuid.ex
By using `Base.encode16(_, case: :lower)`, we're able to remove a bunch of code from `Faker.UUID`.
I've added:
> Simplify the code in Faker.UUID with base encoding

- CHANGELOG.md
- USAGE.md
- lib/faker/cannabis.ex
- lib/faker/cannabis/en.ex
- test/faker/cannabis_test.exs
This PR includes modules for cannabis related data. Around the world, this is a rapidly growing industry and it would be good to have these modules included in faker. 
I've added:
> Cannabis fakes

- CHANGELOG.md
- lib/faker/file.ex
Some functions were using `:atom` which just refers to the `atom` atom, instead of the keyword `atom`.
> Fix atom typespecs

- CHANGELOG.md
- lib/faker/vehicle.ex
This PR adds a missing function to the `Vehicle` module. There is a form of the `Vehicle.En.model` function that takes a make and returns a make belonging to the given model. I missed adding that form to the `Vehicle` module. This PR corrects that.
I've added:
> Fix vehicle model with make

- CHANGELOG.md
- lib/faker/code/iban.ex
- lib/faker/gov/it.ex
I've added:
Doctests should have 4 examples and `Faker.Code.Iban.iban` had extra doctests while `Faker.Gov.It.fiscal_id` was missing 1 doctest.
> Fix Faker.Code.Iban.iban and Faker.Gov.It.fiscal_id doctests

- CHANGELOG.md
- lib/faker/date.ex
This is one of those insidious date issues that only appear on specific dates.
Currently, when `Date.date_of_birth/1` generates a potential date range it will create an "earliest potential date" that is `today + 1`.
https://github.com/elixirs/faker/blob/master/lib/faker/date.ex#L19
This will always be invalid on the last day of the month. In the event the date is invalid a hard coded date of `3/1` is used. This has the side effect of generating a date that has the potential to be outside the allowed date range. I believe the later in the year it is the more likely this is to happen.
This pull request uses Elixir's built in date manipulation functions to properly modify dates. Eliminating the possibility of invalid dates being generated.
I've added:
> Fixed issue with Date.date_of_birth/1 using invalid date range

- CHANGELOG.md
- lib/faker/team.ex
Hi there. By reading the docs for examples on the [Team module](https://hexdocs.pm/faker/Faker.Team.html#content) I've found this mismatch on the examples section.
> The examples were changed between `name/0` and `creature/0`
I've added:
> doc: fix team doc

- CHANGELOG.md
- lib/faker/vehicle.ex
- lib/faker/vehicle/en.ex
Adds:
Having Vehicle makes and models that include hyphens and white space will create more robust tests for `Vehicle` module users. This reflects real world make and model data structures.
> Add Vehicle Makes and Models, module cleanup

- CHANGELOG.md
- README.md
Updated badge on README to use GitHub Actions instead of Travis.
I've added:
> GitHub Actions badge

- CHANGELOG.md
- lib/faker/vehicle.ex
- lib/faker/vehicle/en.ex
Summary of changes:
- Update "Chevy" to the official spelling "Chevrolet"
- Fix spelling of "F-150" (the official name contains a hyphen)
- Fix spelling of "Camaro"
- Fix spelling of "Riviera"
I've added:
> Fix spelling of some vehicle makes/models
