elixirs/faker

lib/faker/shakespeare.ex
test/faker/shakespeare_test.exs

Added Shakespeare module to generate random Shakespeare quotes; also added corresponding tests.

Feature shakespeare

---

README.md

@igas,
I fixed some typos in the README as well as some grammar errors.

'Fixed typos and grammar errors'

---

lib/faker/color.ex
lib/faker/color/en.ex
test/faker/color_test.exs

Hey :wave: 
I've added couple of functions to the color module to return random color names as well as some fancy color names.
I've tried to keep to the conventions I saw in the rest of the code and believe I've added the correct docs directives and tests. I did something slightly different in the color module where I extracted the reference to the localised module to a private function instead, hope this is ok?
Apologies if I've made any silly mistakes as I'm new to elixir and it's my first elixir PR :cold_sweat:
I'd love to hear what you think and hope everything is in order.
Thanks,
.FxN

Added color names and fancy color names

---

README.md

I have to check if the anchors are correct. I didn't include the Locales on purpose, this documentation must be a quick reference.

Documentation readme

---

README.md
lib/faker/file.ex
test/faker/file_test.exs

File is really common, so I added a .... generator :p 
We can discuss about the API if you want, but I think it's fairly simple (not like the date module ...)
Hope you will merge that and I will get a heart !

Generator file

---

.travis.yml
lib/faker/address.ex
lib/faker/avatar.ex
lib/faker/bitcoin.ex
lib/faker/code.ex
lib/faker/internet.ex

As stated in issue #52 , when compiling Faker with Erlang 19.0 I'm getting some warnings about deprecated modules and functions:
<details>
```
==> faker
Compiling 22 files (.ex)
warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
lib/faker/bitcoin.ex:13
warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
lib/faker/bitcoin.ex:17
warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
lib/faker/avatar.ex:43
warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
lib/faker/avatar.ex:48
warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
lib/faker/code.ex:5
warning: …
```

Fix compilation warnings

---

USAGE.md
lib/faker/pokemon.ex
lib/faker/pokemon/en.ex
test/faker/pokemon_test.exs

just added support for this https://github.com/stympy/faker#fakerpokemon

Adding pokemon support

---

USAGE.md

* add all methods to the example
* hide complete numbers with x's in documentation
* adds documentation for #44

Update Usage to include Faker.Phone

---

lib/faker.ex

switch list to map for data structure (closes #58)

---

lib/faker/superhero/en.ex
test/faker/date_test.exs

I haven't modified the changelog, there was already a line for removing those -- it looks like these were only for the new superhero feature.

remove Elixir 1.4.0 compile warnings

---

CHANGELOG.md
USAGE.md
lib/faker/internet.ex
lib/faker/internet/user_agent.ex
test/faker/internet/user_agent_test.exs

Hello, would you be interested in adding user-agent support?
I've added:

Add user agent support

---

CHANGELOG.md
USAGE.md
lib/faker/internet.ex
test/faker/internet_test.exs

Added Faker.Internet.slug implementation

---

CHANGELOG.md
USAGE.md
lib/faker/bitcoin.ex
lib/faker/code/iban.ex
lib/faker/date.ex
lib/faker/datetime.ex
lib/faker/internet.ex
lib/faker/lorem.ex
lib/faker/naivedatetime.ex

<strike>Resolved most of the credo issues, except the few (currently 4) in `lib/faker/lorem.ex` bc I wasn't clever enough to find a nice way to do it quickly.</strike> nvm got em all

credo issues

---

lib/faker/util.ex
lib/faker/util/en.ex
test/faker/util_test.exs

Initial proposal for `Faker.Util` as discussed here: https://github.com/igas/faker/issues/84
Feedback, suggestions, discussions, etc. welcome.
I'll update changelog/readme/usage/etc and check the generated docs after feedback

Add Faker.Util module

---

CHANGELOG.md
USAGE.md
lib/faker/string.ex
test/faker/string_test.exs

Add random string

---

lib/faker/util.ex

fix Util.join docs

---

CHANGELOG.md
lib/faker.ex
lib/faker/address.ex
lib/faker/app.ex
lib/faker/avatar.ex
lib/faker/beer.ex
lib/faker/bitcoin.ex
lib/faker/code.ex
lib/faker/code/iban.ex
lib/faker/color.ex
lib/faker/commerce.ex
lib/faker/commerce/en.ex
lib/faker/company/en.ex
lib/faker/date.ex
lib/faker/datetime.ex
lib/faker/file.ex
lib/faker/internet.ex
lib/faker/lorem.ex
lib/faker/name/en.ex
lib/faker/phone/en_gb.ex
lib/faker/phone/en_us.ex
lib/faker/pizza.ex
lib/faker/random.ex
lib/faker/random/elixir.ex
lib/faker/superhero/en.ex
lib/faker/util.ex
mix.exs
test/faker/pizza_test.exs

Added custom random functions

---

USAGE.md
lib/faker/cat.ex
lib/faker/cat/cat.ex
test/faker/cat_test.exs

#hacktoberfest
I've added:
- [✅] USAGE.md docs if applicable
- [❌] CHANGELOG.md

Adding cats

---

CHANGELOG.md
USAGE.md
lib/faker/star_wars.ex
lib/faker/star_wars/en.ex
test/faker/star_wars_test.exs

Why
---
- Some people like to test with Star Wars data.
This change addresses the need by
---------------------------------
- Create Faker module for random Star Wars data.
I've added:

mFaker Star Wars

---

CHANGELOG.md
lib/faker/date.ex
lib/faker/internet.ex
lib/faker/internet/user_agent.ex
lib/faker/star_wars/en.ex
lib/faker/string.ex

Remove references to random sources other than Faker.*

---

CHANGELOG.md
mix.lock

Changed: Updated dependencies

---

.formatter.exs
CHANGELOG.md

Added: mix format config file

---

CHANGELOG.md
lib/faker/address.ex
test/faker/address_test.exs

I've added:
No dependency geohash implementation. Credited @feyl on this as he/her opened the original PR. Should replace #107.

Geohash support

---

CHANGELOG.md
lib/faker.ex
lib/faker/app.ex
test/faker/app_test.exs

Fixed: generating invalid versions by Faker.App.semver/0

---

test/faker/beer/en_test.exs
test/faker/beer_test.exs
test/faker/color/en_test.exs
test/faker/color/es_test.exs
test/faker/color/pt_br_test.exs
test/faker/color_test.exs

Changed: doctests for color & beer unified in one test

---

lib/faker/code.ex
lib/faker/code/iban.ex
test/faker/code/iban_test.exs
test/faker/code_test.exs

Added: doctests for code

---

lib/faker/gov/us.ex
test/faker/gov/us_test.exs

Added: doctests for Gov.Us

---

lib/faker/avatar.ex
lib/faker/commerce.ex
lib/faker/company.ex
lib/faker/date.ex
lib/faker/industry.ex
lib/faker/internet.ex
lib/faker/internet/en.ex
lib/faker/internet/es.ex
lib/faker/internet/pt_br.ex
lib/faker/lorem/shakespeare.ex
lib/faker/naivedatetime.ex
lib/faker/name.ex
lib/faker/pokemon.ex
lib/faker/random/test.ex
lib/faker/star_wars.ex
lib/faker/string.ex
lib/faker/superhero.ex
lib/faker/superhero/en.ex
lib/faker/team.ex
lib/faker/util/en.ex
test/faker/app_test.exs
test/faker/avatar_test.exs
test/faker/beer_test.exs
test/faker/code_test.exs
test/faker/date_test.exs
test/faker/string_test.exs
test/test_helper.exs

Added: doctests for Avatar and style changes

---

lib/faker/datetime.ex
lib/faker/file.ex
test/faker/file_test.exs
test/faker/gov/us_test.exs

Added: doctests for File

---

CHANGELOG.md
lib/faker/star_wars.ex
lib/faker/star_wars/en.ex
test/faker/star_wars_test.exs

I've added:
ps: another one :+1:

Add StarWars doctests

---

.gitlab-ci.yml

Add gitlab CI

---

lib/faker/app.ex
lib/faker/beer.ex
lib/faker/bitcoin.ex
lib/faker/date.ex
lib/faker/food.ex
lib/faker/food/en.ex
test/faker/bitcoin_test.exs
test/faker/date_test.exs

Doctests should have 4 examples

---

CHANGELOG.md
lib/faker/team.ex
lib/faker/team/en.ex
test/faker/team_test.exs

Add Team doctests

---

CHANGELOG.md
lib/faker/date.ex
lib/faker/internet.ex
lib/faker/internet/en.ex
lib/faker/internet/es.ex
lib/faker/internet/pt_br.ex
test/faker/internet_test.exs

Add internet doctests

---

CHANGELOG.md
lib/faker/date.ex
lib/faker/nato.ex
lib/faker/uuid.ex
test/faker/nato_test.exs

Add nato doctests

---

CHANGELOG.md
lib/faker/string.ex
test/faker/string_test.exs

Add Faker.String doctest

---

CHANGELOG.md
USAGE.md

Add missing docs in usage.md

---

.gitignore
CHANGELOG.md
lib/faker/util.ex
test/faker/util_test.exs

Added: Faker.Util doctests

---

CHANGELOG.md
lib/faker/internet/user_agent.ex
test/faker/internet/user_agent_test.exs

Added: Faker.Internet.UserAgent doctests

---

lib/faker/phone/en_gb.ex
lib/faker/phone/en_us.ex
test/faker/address_test.exs
test/faker/datetime_test.exs
test/faker/internet_test.exs
test/faker/lorem_test.exs
test/faker/naivedatetime_test.exs
test/faker/phone/en_gb_test.exs
test/faker/phone/en_us_test.exs
test/faker/phone_test.exs
test/faker/pokemon_test.exs
test/faker/star_wars_test.exs
test/faker/uuid_test.exs

Added: Faker.Phone doctests

---

.travis.yml

Added: Elixir 1.7 support

---

CHANGELOG.md
lib/faker/util.ex

Generates some number of elements that are all unique
I've added:

introduce Util.sample_uniq/2

---

CHANGELOG.md
lib/faker/team/pt_br.ex
test/faker/team_test.exs

Add Faker.Team.PtBr

---

CHANGELOG.md
lib/faker/food.ex
lib/faker/food/en.ex

Add Faker.Food.En.sushi()

---

CHANGELOG.md
lib/faker/beer.ex
lib/faker/beer/en.ex

Add Faker.Beer.brand/0

---

CHANGELOG.md
lib/faker.ex

Fix Kernel.function_exported? call

---

CHANGELOG.md
lib/faker/star_wars/en.ex

Fixed typo for Beru Lars and changed Palpatine to Sheev Palpatine
I've added:

Fixed typo in Faker.Starwars

---

lib/faker/address/en.ex
lib/faker/address/es.ex
lib/faker/name/en.ex

Some minor problems have been fixed.

Fix minor problems

---

CHANGELOG.md
mix.exs

Added: Vitor Oliveira as a maintainer

---

CHANGELOG.md
USAGE.md
lib/faker/vehicle.ex
lib/faker/vehicle/en.ex
test/faker/vehicle_test.exs

Added the `Faker.Vehicle` module which adds several functions to generate realistic vehicle data.

Add Faker.Vehicle

---

.travis.yml
CHANGELOG.md

Added: Elixir 1.9 support

---

CHANGELOG.md
USAGE.md
lib/faker/color/fr.ex
test/faker/color_test.exs

I've added:
--------------
Hello! 
It's a small contribution because I don't have much time tonight. I might add more categories next time.
Thanks

Colors for French language

---

CHANGELOG.md
USAGE.md
lib/faker/blockchain/ethereum.ex
test/faker/blockchain/ethereum_test.exs

I've added:
- [Faker.Blockchain.Ethereum](lib/faker/blockchain/ethereum.ex)

Added: Faker.Blockchain.Ethereum

---

CHANGELOG.md
USAGE.md
lib/faker/finance.ex
lib/faker/finance/stock.ex
test/faker/finance_test.exs

Add basic financial data: stock RIC

---

CHANGELOG.md
USAGE.md
lib/faker/color/de.ex

Add german colors

---

CHANGELOG.md
USAGE.md
lib/faker/gov/it.ex
lib/faker/util.ex
test/faker/gov/it_test.exs

Add implementation of italian fiscal id

---

CHANGELOG.md
CONTRIBUTING.md
README.md

Add CONTRIBUTING and update README

---

CHANGELOG.md
lib/faker/address/it.ex

Add missing Faker.Address.It doctests

---

CHANGELOG.md
lib/faker/name/hy.ex

Add missing Faker.Name.Hy.suffix doctests

---

CHANGELOG.md
lib/faker/nato.ex

Remove extra doctests in Faker.Nato.format

---

.travis.yml
CHANGELOG.md
mix.exs

Remove support for Elixir 1.4

---

mix.exs

Bumped version to v0.14.0

---

CHANGELOG.md
README.md
mix.exs

Reset CHANGELOG and README

---

CHANGELOG.md
USAGE.md
lib/faker/currency.ex
test/faker/currency_test.exs

I've added the module `Currency`

feat: add module currency

---

CHANGELOG.md
USAGE.md
lib/faker/address/pt_br.ex
test/faker/address_test.exs

Add Brazilian generator (Address)

---

CHANGELOG.md
README.md
lib/faker/date.ex
mix.exs

I've added:
- ~[ ] CHANGELOG.md~

Reset for new version

---

CHANGELOG.md
USAGE.md
lib/faker/aws/en.ex
lib/faker/aws/fr.ex
test/faker/aws_test.exs

I've added:
- Faker.Aws.Fr.region_name/0
- doctests Faker.Aws.Fr

AWS FR (added region_name/0)

---

CHANGELOG.md
lib/faker/aws/en.ex

I've added:
- AWS S3 actions
[Documentation for AWS S3 Actions](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations.html)
Future:
- I will implement similar PRs later this month for AWS Services such as EC2, DynamoDB, RDS, etc.
Reason:
- Those functions will be used by the function iam_policy/0, it will create a JSON file containing a random AWS IAM policy.

AWS S3 Actions

---

.travis.yml
CHANGELOG.md

Added: Elixir 1.11 to CI

---

CHANGELOG.md
USAGE.md
lib/faker/airports/pt_br.ex
test/faker/airports_test.exs

feat: new feature, adding module airports PtBr

---

CHANGELOG.md
README.md
mix.exs

Bump version to v0.16.0

---

CHANGELOG.md
README.md
lib/faker.ex
lib/faker/blockchain/ethereum.ex
lib/faker/color/de.ex
lib/faker/color/en.ex
lib/faker/color/pt_br.ex
lib/faker/commerce/en.ex
lib/faker/company/en.ex
lib/faker/internet.ex
lib/faker/nato.ex
lib/faker/superhero.ex
lib/faker/util.ex
lib/faker/vehicle.ex
mix.exs

List of changes:
- Fix typos
- Use common source url
- Set readme as main html page
- Add changelog to html doc
- Add source reference
- Add extra files to package
- Add maintainers to package
- Badges and more badges
I've added:

Misc doc changes

---

.github/workflows/ci.yaml
CHANGELOG.md
README.md
mix.exs

I've added:
- ~[ ] CHANGELOG.md~

Release 0.17.0

---

CHANGELOG.md
lib/faker/address/pt_br.ex

Update address ptbr module documentation

---

CHANGELOG.md
USAGE.md
lib/faker/fruit/en.ex
test/faker/fruit_test.exs

Add english fruits

---

CHANGELOG.md
lib/faker/date.ex

fix: date_of_birth invalid date due to leap year

---

CHANGELOG.md
README.md
mix.exs

release: v0.18.0
